FROM python:3.10.13 AS builder
WORKDIR /app
COPY ./requirements.txt /app
RUN pip install -r /app/requirements.txt

FROM python:3.10.13-slim-bullseye
EXPOSE 8080
COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
WORKDIR /app
COPY ./setup.sh /app
RUN apt-get update && apt-get install -y --no-install-recommends git \
    && rm -rf /var/lib/apt/lists/* /tmp/* \
    && chmod +x /app/setup.sh
ENTRYPOINT ["/app/setup.sh"]