[project]
name = "dolinuxradar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "feedparser>=6.0.11",
    "python-dotenv>=1.1.0",
    "python-telegram-bot[job-queue,rate-limiter,webhooks]>=22.0",
    "requests>=2.32.3",
]
